name: ALZ Zone-1 pipeline

on:
  push:
    branches:
      - "alz-slim"
    paths:
      - 'infra-as-code/bicep/modules/roleAssignments/**'
      - 'infra-as-code/bicep/modules/policy/assignments/**'

env:
  ManagementGroupPrefix: "zmoalz"
  TopLevelManagementGroupDisplayName: "Azure Landing Zones"
  Location: "norwayeast"
  LoggingSubId: "44273f48-4fd6-4144-b278-d19d201ad922"
  LoggingResourceGroupName: "zmoalz-centrallogging"
  HubNetworkSubId: "0f18a4f9-2e78-43d0-b06a-6a490469a7a6"
  HubNetworkResourceGroupName: "Hub_Networking"
  RoleAssignmentManagementGroupId: "zmoalz-platform"
  PrivateSpokeNetworkSubId: "6a4b4279-20aa-4245-8b88-64f9f491b9b2"
  PrivateSpokeNetworkResourceGroupName: "Private_LZ1_Networking"
  PublicSpokeNetworkSubId: "1e63056d-66f8-4d36-8454-b4375eb8578f"
  PublicSpokeNetworkResourceGroupName: "Public_LZ1_Networking"
  runNumber: ${{ github.run_number }}

jobs:
  bicep_tenant_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Deploy Role Assignment
        id: create_role_assignment
        uses: azure/arm-deploy@v1
        with:
          scope: managementgroup
          managementGroupId: ${{ env.RoleAssignmentManagementGroupId }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/roleAssignments/roleAssignmentManagementGroup.bicep
          parameters: infra-as-code/bicep/modules/roleAssignments/parameters/roleAssignmentManagementGroup.servicePrincipal.parameters.all.json
          deploymentName: create_role_assignment-${{ env.runNumber }}
          failOnStdErr: false

      - name: Deploy Default Policy Assignments
        id: create_policy_assignments
        uses: azure/arm-deploy@v1
        with:
          scope: managementgroup
          managementGroupId: ${{ env.ManagementGroupPrefix }}
          region: ${{ env.Location }}
          template: infra-as-code/bicep/modules/policy/assignments/alzDefaults/alzDefaultPolicyAssignments.bicep
          parameters: infra-as-code/bicep/modules/policy/assignments/alzDefaults/parameters/alzDefaultPolicyAssignments.parameters.all.json
          deploymentName: create_policy_assignments-${{ env.runNumber }}
          failOnStdErr: false